language: groovy
jdk:
- oraclejdk8
sudo: false
branches:
  only:
  - master
  - grails3
before_install:
 - wget -q https://raw.githubusercontent.com/AtlasOfLivingAustralia/travis-build-configuration/master/ala_common.sh
 - chmod +x ala_common.sh
 - source ./ala_common.sh

 - ala_travis_grails_setup_env

script:
 - ala_travis_grails_build

env:
  global:
  - secure: JKvwCLZapyEjcNF+da5s1lM0MhYW2ZmkBJbmj+A9G3CkxPNnhGB9tpRO1daIFSgYuFnZxER3kkqN+gYNWSzhxY9DpRxRt+j/X46RhD8g5NNrImXhwkYznsQPE9u9uoP6HyEbKrn+MelTBE5GVmpf1zAmG8j87VbsSJUdUm5t0Ys=
  - secure: PlC/+3gKO3rLwzyDUh6YiDuTBgqGEF0apz/8yiLz/5qqfnPECH5CNydImq/RLwkietyzteSLhpslp2CvAIc7DcX0aOsPF4H/YBWpxoWkk0lARWCswNMTc/46+orpfN5WvmZRkzEyQr0gm4hoYcjtV5BuEsTN8XAkh1+D0L6SLNM=
